= Spring Cloud for Amazon Web Services

include::intro_zh.adoc[]

= 检出和构建代码
检出项目以及构建代码, 按照以下步骤完成:

--------------------------------------------------------------
git clone https://github.com/spring-cloud/spring-cloud-aws.git
cd spring-cloud-aws
mvn package
--------------------------------------------------------------

如果在构建代码的时候遇到内存不够的问题, 请增加分配给Maven的内存:

-------------------------------------------
MAVEN_OPTS='-XX:MaxPermSize=258m -Xmx1024m'
-------------------------------------------

构建与安装jar包到本地Maven缓存:

-----------
mvn install
-----------

= 构建文档
Documentation can be built by activating the `docs`profile in the maven
build. If there is an ruby error like

--------------------------------------------------------------
LoadError: no such file to load -- asciidoctor
--------------------------------------------------------------

then the user must install the _asciidoctor_ gem and set the environment
variable `GEM_HOME`to the ruby gem folder. For example:

-------------------------------------------------------------
  # Get gem info
  gem environment

  export GEM_HOME=<PATH FOR GEM ENVIRONMENT>

-------------------------------------------------------------

= 使用 IntelliJ IDEA
Spring Cloud AWS使用 http://www.jetbrains.com/idea/[IntelliJ IDEA] 进行开发. 
如果想创建所有 http://www.jetbrains.com/idea/[IntelliJ IDEA] 项目文件, 
首先在Idea环境下导入Maven项目文件.

_Note:_ Please make sure to revert all changes in the .idea config file
directory, as the maven plugin overwrites the configuration files kept
in the scm.

= 运行集成测试

Spring Cloud AWS contains a test-suite which runs integration tests to
ensure compatibility with the Amazon Web Services. In order to run the
integration tests, the build process has to create different resources
on the Amazon Webservice platform (Amazon EC2 instances, Amazon RDS
instances, Amazon S3 Buckets, Amazon SQS Queues). Creating these
resources takes time and costs money, because every instance creation is
charged with a one hour usage. Therefore Spring Cloud AWS does not
execute the integration tests by default.

In order to execute the integration tests you have to create two
configuration files that configure the necessary parameters to build the
environment.

Please create a new file named access.properties. This file must contain
three properties named accessKey,secretKey and rdsPassword. These two
properties accessKey and secretKey are account/user specific and should
never be shared to anyone. To retrieve these settings you have to open
your account inside the AWS console and retrieve them through the
https://portal.aws.amazon.com/gp/aws/securityCredentials[Security
Credentials Page]. _Note:_ In general we recommend that you use an
https://aws.amazon.com/iam/[Amazon IAM] user instead of the account
itself. The last password rdsPassword is used to access the database
inside the integration tests. This password has a minimum length of 8
characters.

An example file will look like this

-------------------------------------------
cloud.aws.credentials.accessKey=ilaugsjdlkahgsdlaksdhg
cloud.aws.credentials.secretKey=aöksjdhöadjs,höalsdhjköalsdjhasd+
rdsPassword=someVerySecretPassword
-------------------------------------------

Also you have to create another file named mail.properties which will
provide the sender and recipient mail address to test the
https://aws.amazon.com/ses/[Amazon Simple E-Mail Service]. These two
addresses must be verified for the Amazon SES Service.

An example file will have the following contents

----------------------------
senderAddress=foo@bar.com
recipientAddress=baz@buz.com
----------------------------

After creating both files and storing them outside the project (or
inside the project, they are ignored in git) you have to provide the
configuration directory when running the build. Providing these
configuration settings will automatically execute the integration tests.

To build with the integration tests you must execute

-----------------------------------------------------------------------------------------------------
mvn verify -Dels.config.dir=/Users/foo/config/dir
(on windows you will also need a leading slash before the drive letter e.g. /C:/users/foo/config/dir)
-----------------------------------------------------------------------------------------------------

The integration test will create an
https://aws.amazon.com/de/cloudformation/[Amazon Web Services
CloudFormation] stack and execute the tests. The stack is destroyed
after executing the tests (either successful or failed) to ensure that
there are no unnecessary costs.

= 集成测试成本
一次集成测试的成本大约$0.40/小时以内 (excl. VAT).


= 基于AWS开发

During development it might be time-consuming to run the integration
tests regularly. In order to create a stack only once, and reuse them
for the tests run, you have to create the stack manually using the
template found in /spring-cloud-aws-integration-test/src/test/resources.
You will need to create the stack with the name "IntegrationTestStack"
to ensure that the integration tests will re-use the stack.

= 保持联系

Spring Cloud 团队 https://twitter.com/springcentral[Twitter]

以下是个体贡献者以及他们的社交媒体账号：

* Agim Emruli (http://twitter.com/aemruli[Twitter] /
http://de.linkedin.com/in/agimemruli[LinkedIn])
* Alain Sahli (http://twitter.com/sahlialain[Twitter] /
http://ch.linkedin.com/in/asahli[LinkedIn])
* Christian Stettler (http://twitter.com/chrisstettler[Twitter])

== 给Spring Cloud AWS项目贡献

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing.adoc[]
